import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { OrderTimerBadge } from "./OrderTimerBadge";
export function KDSBoard({ orders, onUpdateStatus }) {
    const pending = orders.filter(o => o.status === 'PENDING');
    const preparing = orders.filter(o => o.status === 'PREPARING');
    const ready = orders.filter(o => o.status === 'READY');
    const Column = ({ title, items, nextStatus, color }) => (_jsxs("div", { className: "glass-panel", style: { flex: 1, display: 'flex', flexDirection: 'column', gap: '16px', background: 'rgba(0,0,0,0.4)', padding: '24px' }, children: [_jsxs("h3", { style: { margin: 0, borderBottom: `2px solid ${color}`, paddingBottom: '12px' }, children: [title, " (", items.length, ")"] }), _jsxs("div", { style: { display: 'flex', flexDirection: 'column', gap: '12px', overflowY: 'auto' }, children: [items.map((o) => (_jsxs("div", { className: "glass-panel", style: { padding: '16px', background: 'var(--bg-card)' }, children: [_jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', marginBottom: '12px' }, children: [_jsx("span", { style: { fontWeight: 700, fontSize: '18px' }, children: o.orderNo }), _jsx(OrderTimerBadge, { placedAt: o.placedAt, status: o.status })] }), _jsx("div", { style: { color: 'var(--text-muted)', marginBottom: '16px' }, children: o.channel }), nextStatus && (_jsxs("button", { className: "rgb-button", style: { padding: '8px 16px', fontSize: '14px', width: '100%', borderColor: color }, onClick: () => onUpdateStatus(o.id, nextStatus), children: ["Move to ", nextStatus] }))] }, o.id))), items.length === 0 && _jsx("div", { style: { color: 'var(--text-muted)', textAlign: 'center', marginTop: '20px' }, children: "No orders" })] })] }));
    return (_jsxs("div", { style: { display: 'flex', gap: '24px', height: '100%' }, children: [_jsx(Column, { title: "New / Pending", items: pending, nextStatus: "PREPARING", color: "var(--accent-pink)" }), _jsx(Column, { title: "Preparing", items: preparing, nextStatus: "READY", color: "var(--accent-blue)" }), _jsx(Column, { title: "Ready for Pickup", items: ready, nextStatus: "COMPLETED", color: "var(--accent-green)" })] }));
}
